summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-freebsd-13.4-amd64/releases/download/2025.07.22/pkg-config-0.29.2-freebsd-13.4-amd64.release.tar.xz 
bin-sha: 687d4889f0b6718bc6ead04151b1dd731329e0e94c1cbb1449538fb60795f094
